title: Gennadiy Khatuntsev
description: Software Engineer
avatar: https://avatars1.githubusercontent.com/u/1467622

author:
  name: Gennadiy Khatuntsev
  email: e.steelcat@gmail.com

footer-links:
  github: stee1cat
  linkedin: khatuntsev

disqus:
google_analytics: UA-138989703-1
yandex_metrika: 53423350

url: https://khatuntsev.dev
permalink: /:year-:month-:day/:title/
baseurl: ""

version: v1.2.0
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  sass_dir: _sass
  style: compressed

include:
  - _pages

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

exclude:
  - .idea
  - node_modules
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

paginate: 5
